# Generated by Django 5.1 on 2024-09-10 00:47

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New Part'), (2, 'In Design'), (3, 'In Design Review'), (4, 'Design Review Complete'), (5, 'Manufacturing Review Complete'), (6, 'In Manufacturing'), (7, 'Manufacturing Complete'), (8, 'Quality Check Complete'), (9, 'In Assembly'), (10, 'Assembly Completed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_placed_date', models.DateField(blank=True, null=True, verbose_name='Order Placed Date')),
                ('order_recv_date', models.DateField(blank=True, null=True, verbose_name='Order Received Date')),
                ('tracking', models.CharField(blank=True, max_length=200, null=True)),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New Order'), (2, 'Ready to Order'), (3, 'Order Placed'), (4, 'Order Received')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('unit_price', models.FloatField()),
                ('justification', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_site.order')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New Part'), (2, 'In Design'), (3, 'In Design Review'), (4, 'Design Review Complete'), (5, 'Manufacturing Review Complete'), (6, 'In Manufacturing'), (7, 'Manufacturing Complete'), (8, 'Quality Check Complete'), (9, 'In Assembly'), (10, 'Assembly Completed')], default=1)),
                ('drawing', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('./'), upload_to='uploads/<django.db.models.fields.CharField>/')),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('mfg_type', models.CharField(blank=True, choices=[('CNC_MILL', 'CNC Mill'), ('MANUAL_MILL', 'Manual Mill'), ('ROUTER', 'Router'), ('LATHE', 'Lathe'), ('3D_PRINT', '3D Printer'), ('LASER_CUT', 'Laser Cutter')], max_length=200, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_site.assembly')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_site.project'),
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('assembly_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts_site.assembly')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='parts_site.assembly')),
            ],
            bases=('parts_site.assembly',),
        ),
    ]
