# Generated by Django 5.1 on 2024-09-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_site', '0002_item_requested_by_part_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.CharField>/'),
        ),
    ]
