# Generated by Django 5.1 on 2024-09-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_site', '0004_alter_part_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
