# Generated by Django 5.1 on 2025-09-15 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_site', '0005_alter_part_drawing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='drawing',
        ),
        migrations.RemoveField(
            model_name='part',
            name='material',
        ),
        migrations.RemoveField(
            model_name='part',
            name='mfg_type',
        ),
        migrations.RemoveField(
            model_name='part',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='status',
        ),
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(default='A', max_length=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New Part'), (2, 'In Design'), (3, 'In Design Review'), (4, 'Design Review Complete'), (5, 'Manufacturing Review Complete'), (6, 'In Manufacturing'), (7, 'Manufacturing Complete'), (8, 'Quality Check Complete'), (9, 'In Assembly'), (10, 'Assembly Completed')], default=1)),
                ('drawing', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('mfg_type', models.CharField(blank=True, choices=[('CNC_MILL', 'CNC Mill'), ('MANUAL_MILL', 'Manual Mill'), ('ROUTER', 'Router'), ('LATHE', 'Lathe'), ('3D_PRINT', '3D Printer'), ('LASER_CUT', 'Laser Cutter')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='parts_site.part')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('part', 'revision_number')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='latest_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_latest', to='parts_site.partrevision'),
        ),
    ]
