# Generated by Django 5.1 on 2025-11-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_site', '0006_remove_part_drawing_remove_part_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrevision',
            options={'ordering': ['-revision_number']},
        ),
        migrations.AddField(
            model_name='assembly',
            name='onshape_document_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='onshape_element_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='onshape_folder_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='onshape_element_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onshape_folder_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
