# Generated by Django 5.1 on 2025-12-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_site', '0007_alter_partrevision_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
